title = "Docksal Documentation"
languageCode = "en-us"
theme = "learn"
pygmentsCodeFences = "true"
contentDir = "docs"
baseURL = "https://jddoesdev.github.io/docksal-training/"
canonifyURLs = "true"

[params]
  showVisitedLinks = true
  description = "Docksal training guide"

  # Custom CSS => statis/css/theme-docksal.css
  themeVariant = "docksal"

  google_tag_manager = ""

  version = "v0.0.1"

  [[params.versions]]
  version = "v0.0.1"
  branch = "v0.0.1"
  url = ""

[outputs]
  home = [ "AMP", "HTML", "JSON", "Sitemap"]

[menu]
  [[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Guide Github repo"
  identifier = "ds"
  url = "https://github.com/jddoesdev/docksal-training"
  weight = 10

  [[menu.shortcuts]]
  name = "Official Docksal documentation"
  identifier = "of"
  url = "https://docs.docksal.io"
  weight = 20

  [[menu.shortcuts]]
  name = "Docksal Project"
  identifier = "do"
  url = "https://docksal.io"
  weight = 0
